spring:
  application:
    name: mediaassistant
  profiles:
    include:
      - ollama
      - gemini
  datasource:
    url: jdbc:postgresql://localhost:5432/mediaassistant
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
