spring:
  ai:
    google:
      genai:
        api-key: ${GOOGLE_GENAI_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite
            temperature: 0.4
            maxOutputTokens: 2048
            top-p: 0.85
