spring:
  application:
    name: mediaassistant
  profiles:
    include:
      - ollama
      - gemini
  datasource:
    url: jdbc:postgresql://localhost:5432/mediaassistant
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://shiny-engine-46j44p99xp3jx46-8090.app.github.dev/realms/medassistant
          #issuer-uri: http://localhost:8090/realms/medassistant